### ISSUE TITLE
Lizenzwahl - Korrektur des "licence"-files

### ISSUE THREAD

**Issue by uni-it-law** [RZ-BY/Leitfaden-Barrierefreiheit#1]
Nach dem Inhalt ist das Werk unter  Creative Commons Namensnennung - Nicht-kommerziell - Weitergabe unter gleichen Bedingungen 4.0 International Lizenz.

Im Lizenzfile selbst jedoch Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International Lizenz.

**Comment by xwolfde** [comment]
fixed. (Muss aber  nochmal ein besseres Format suchen; Die Umbrüche sind unschön.)
