### ISSUE TITLE
Anpassung an die neue BayBITV

### ISSUE THREAD

**Issue by uni-it-law** [RZ-BY/Leitfaden-Barrierefreiheit#25]
Seit 1. Oktober wurde die BayBITV angepasst. Die Änderungen werden zunächst nicht im Master sondern in Dev eingefügt.

**Comment by xwolfde** [comment]
hab die push requests in den dev branch gemergt

**Comment by uni-it-law** [comment]
Gibt noch etwas Nachschlag.
